export const countries = [
  { iso_2_alpha: 'in', countryName: 'India' },
  { iso_2_alpha: 'au', countryName: 'Australia' },
  { iso_2_alpha: 'bd', countryName: 'Bangladesh' },
  { iso_2_alpha: 'cn', countryName: 'China' },
  { iso_2_alpha: 'hk', countryName: 'Hong Kong' },
  { iso_2_alpha: 'id', countryName: 'Indonesia' },
  { iso_2_alpha: 'jp', countryName: 'Japan' },
  { iso_2_alpha: 'kr', countryName: 'South Korea' },
  { iso_2_alpha: 'my', countryName: 'Malaysia' },
  { iso_2_alpha: 'nz', countryName: 'New Zealand' },
  { iso_2_alpha: 'ph', countryName: 'Philippines' },
  { iso_2_alpha: 'pk', countryName: 'Pakistan' },
  { iso_2_alpha: 'sg', countryName: 'Singapore' },
  { iso_2_alpha: 'th', countryName: 'Thailand' },
  { iso_2_alpha: 'tw', countryName: 'Taiwan' },
  { iso_2_alpha: 'vn', countryName: 'Vietnam' },
  { iso_2_alpha: 'ae', countryName: 'United Arab Emirates' },
  { iso_2_alpha: 'il', countryName: 'Israel' },
  { iso_2_alpha: 'lb', countryName: 'Lebanon' },
  { iso_2_alpha: 'sa', countryName: 'Saudi Arabia' },
  { iso_2_alpha: 'tr', countryName: 'Turkey' },
  { iso_2_alpha: 'bw', countryName: 'Botswana' },
  { iso_2_alpha: 'eg', countryName: 'Egypt' },
  { iso_2_alpha: 'et', countryName: 'Ethiopia' },
  { iso_2_alpha: 'gh', countryName: 'Ghana' },
  { iso_2_alpha: 'ke', countryName: 'Kenya' },
  { iso_2_alpha: 'ma', countryName: 'Morocco' },
  { iso_2_alpha: 'na', countryName: 'Namibia' },
  { iso_2_alpha: 'ng', countryName: 'Nigeria' },
  { iso_2_alpha: 'sn', countryName: 'Senegal' },
  { iso_2_alpha: 'tz', countryName: 'Tanzania' },
  { iso_2_alpha: 'ug', countryName: 'Uganda' },
  { iso_2_alpha: 'za', countryName: 'South Africa' },
  { iso_2_alpha: 'zw', countryName: 'Zimbabwe' },
  { iso_2_alpha: 'at', countryName: 'Austria' },
  { iso_2_alpha: 'be', countryName: 'Belgium' },
  { iso_2_alpha: 'bg', countryName: 'Bulgaria' },
  { iso_2_alpha: 'ch', countryName: 'Switzerland' },
  { iso_2_alpha: 'cz', countryName: 'Czechia' },
  { iso_2_alpha: 'de', countryName: 'Germany' },
  { iso_2_alpha: 'ee', countryName: 'Estonia' },
  { iso_2_alpha: 'es', countryName: 'Spain' },
  { iso_2_alpha: 'fi', countryName: 'Finland' },
  { iso_2_alpha: 'fr', countryName: 'France' },
  { iso_2_alpha: 'gb', countryName: 'United Kingdom' },
  { iso_2_alpha: 'gr', countryName: 'Greece' },
  { iso_2_alpha: 'hu', countryName: 'Hungary' },
  { iso_2_alpha: 'ie', countryName: 'Ireland' },
  { iso_2_alpha: 'it', countryName: 'Italy' },
  { iso_2_alpha: 'lt', countryName: 'Lithuania' },
  { iso_2_alpha: 'lv', countryName: 'Latvia' },
  { iso_2_alpha: 'nl', countryName: 'Netherlands' },
  { iso_2_alpha: 'no', countryName: 'Norway' },
  { iso_2_alpha: 'pl', countryName: 'Poland' },
  { iso_2_alpha: 'pt', countryName: 'Portugal' },
  { iso_2_alpha: 'ro', countryName: 'Romania' },
  { iso_2_alpha: 'ru', countryName: 'Russia' },
  { iso_2_alpha: 'se', countryName: 'Sweden' },
  { iso_2_alpha: 'si', countryName: 'Slovenia' },
  { iso_2_alpha: 'sk', countryName: 'Slovakia' },
  { iso_2_alpha: 'ua', countryName: 'Ukraine' },
  { iso_2_alpha: 'ar', countryName: 'Argentina' },
  { iso_2_alpha: 'br', countryName: 'Brazil' },
  { iso_2_alpha: 'ca', countryName: 'Canada' },
  { iso_2_alpha: 'cl', countryName: 'Chile' },
  { iso_2_alpha: 'co', countryName: 'Colombia' },
  { iso_2_alpha: 'cu', countryName: 'Cuba' },
  { iso_2_alpha: 'mx', countryName: 'Mexico' },
  { iso_2_alpha: 'pe', countryName: 'Peru' },
  { iso_2_alpha: 'us', countryName: 'United States' },
  { iso_2_alpha: 've', countryName: 'Venezuela' },
];
